[build-system]
requires = ["setuptools >= 38.6", "pip >= 10"]
build-backend = "setuptools.build_meta"

[project]
name = "pysatMissions"
version = "0.3.4"
description = "Mission Planning toolkit for pysat"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
    {name = "Jeff Klenzing", email = "pysat.developers@gmail.com"}
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Topic :: Scientific/Engineering :: Astronomy",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering :: Atmospheric Science",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: BSD License",
  "Natural Language :: English",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows"
]
keywords = [
  "pysat",
  "ionosphere",
  "cubesat",
  "satellite",
  "ephemeris",
  "orbit",
  "mission-planning"
]
dependencies = [
  "geospacepy",
  "numpy",
  "pandas",
  "pysat >= 3.0.4",
  "pyEphem",
  "sgp4 >= 2.7",
  "skyfield"
]

[project.optional-dependencies]
aacgmv2 = ["aacgmv2"]
apexpy = ["apexpy"]
OMMBV = ["OMMBV"]
test = [
  "coveralls < 3.3",
  "flake8",
  "flake8-docstrings",
  "hacking >= 1.0",
  "pytest",
  "pytest-cov",
  "pytest-ordering"
]
doc = [
  "extras_require",
  "ipython",
  "m2r2",
  "numpydoc",
  "pyproject_parser",
  "sphinx",
  "sphinx_rtd_theme"
]

[project.urls]
Documentation = "https://pysatmissions.readthedocs.io/en/latest/"
Source = "https://github.com/pysat/pysatMissions"

[tool.coverage.report]

[tool.pytest.ini_options]
addopts = "--cov=pysatMissions"
markers = [
  "all_inst",
  "download",
  "no_download",
  "load_options",
  "first",
  "second"
]
