# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pytest with Flake8

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        numpy_ver: ["latest"]
        include:
          - python-version: "3.8"
            numpy_ver: "1.20"
            os: "ubuntu-latest"

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }} with numpy ${{ matrix.numpy_ver }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install with NEP29 dependencies
      if: ${{ matrix.numpy_ver != 'latest'}}
      run: |
        pip install --no-binary :numpy: numpy==${{ matrix.numpy_ver }}
        # Force install version compatible with NEP29
        pip install "pandas<1.5"
        pip install --upgrade-strategy only-if-needed .[test]

    - name: Install with standard dependencies
      if: ${{ matrix.numpy_ver == 'latest'}}
      run: pip install .[test]

    - name: Install aacgmv2
      # Optional package, continue with tests if install fails
      continue-on-error: true
      run: pip install aacgmv2 --no-binary==aacgmv2

    - name: Install apexpy
      # Optional package, continue with tests if install fails
      continue-on-error: true
      run: pip install apexpy --no-binary==apexpy

    - name: Install OMMBV
      # Optional package, continue with tests if install fails
      continue-on-error: true
      run: pip install OMMBV --no-binary==OMMBV

    - name: Set up pysat
      run: |
        mkdir pysatData
        python -c "import pysat; pysat.params['data_dirs'] = 'pysatData'"

    - name: Test PEP8 compliance
      run: flake8 . --count --select=D,E,F,H,W --show-source --statistics

    - name: Evaluate complexity
      run: flake8 . --count --exit-zero --max-complexity=10 --statistics

    - name: Test with pytest
      run: pytest

    - name: Publish results to coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --rcfile=setup.cfg --service=github
